// <auto-generated />
using System;
using BaseLineProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaseLineProject.Migrations
{
    [DbContext(typeof(FormDBContext))]
    [Migration("20241027083730_addsystemtbl")]
    partial class addsystemtbl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BaseLineProject.Models.SystemMenuModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("MENU_DESC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MENU_LINK")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MENU_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ROLE_ID")
                        .HasColumnType("varchar(75)");

                    b.Property<int>("TAB_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("ID")
                        .HasName("PK_MENU_Seq");

                    b.ToTable("SystemMenuTbl");
                });

            modelBuilder.Entity("BaseLineProject.Models.SystemTabModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ROLE_ID")
                        .HasColumnType("varchar(75)");

                    b.Property<string>("TAB_DESC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TAB_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("ID")
                        .HasName("PK_TAB_Seq");

                    b.ToTable("SystemTabTbl");
                });

            modelBuilder.Entity("BaseLineProject.Models.dbSliderImg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FILE_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<byte[]>("IMG_DESC")
                        .HasColumnType("MediumBlob");

                    b.Property<byte[]>("SLIDE_IMG_BLOB")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("ID")
                        .HasName("PK_SliderImg");

                    b.ToTable("dbSliderImg");
                });
#pragma warning restore 612, 618
        }
    }
}
