// <auto-generated />
using System;
using BaseLineProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaseLineProject.Migrations
{
    [DbContext(typeof(FormDBContext))]
    [Migration("20251211031807_addtaxconfigdb")]
    partial class addtaxconfigdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BaseLineProject.Models.SystemMenuModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("MENU_DESC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MENU_LINK")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MENU_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ROLE_ID")
                        .HasColumnType("varchar(75)");

                    b.Property<int>("TAB_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("ID")
                        .HasName("PK_MENU_Seq");

                    b.ToTable("SystemMenuTbl");
                });

            modelBuilder.Entity("BaseLineProject.Models.SystemTabModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ROLE_ID")
                        .HasColumnType("varchar(75)");

                    b.Property<string>("TAB_DESC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TAB_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("ID")
                        .HasName("PK_TAB_Seq");

                    b.ToTable("SystemTabTbl");
                });

            modelBuilder.Entity("BaseLineProject.Models.dbCompanySeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_Company_Seq");

                    b.ToTable("dbCompany_seq");
                });

            modelBuilder.Entity("BaseLineProject.Models.dbCustomer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BANK_BRANCH")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BANK_COUNTRY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BANK_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BANK_NUMBER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BL_FLAG")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("COMPANY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("COMPANY_ID")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CUST_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EDP")
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("FILE_AKTA")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_AKTA_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_KTP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_KTP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_NIB")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_NIB_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_NPWP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_NPWP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_REKENING")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_REKENING_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_SIUP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_SIUP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_SKT")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_SKT_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_SPPKP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_SPPKP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_TDP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_TDP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("KTP")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NPWP")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("PHONE1")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PHONE2")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("REG_DATE")
                        .HasColumnType("date");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("VA1")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VA1NOTE")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VA2")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VA2NOTE")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("address")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("city")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("customertype")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("discount_customer")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("isApproved")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("isApproved2")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("postal")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("province")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("store_area")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("taxflagpercentage")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("totalstoreconfig")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_Customer");

                    b.ToTable("dbCustomer");
                });

            modelBuilder.Entity("BaseLineProject.Models.dbCustomerSeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_Cust_Seq");

                    b.ToTable("dbCustomer_seq");
                });

            modelBuilder.Entity("BaseLineProject.Models.dbSliderImg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FILE_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<byte[]>("IMG_DESC")
                        .HasColumnType("MediumBlob");

                    b.Property<byte[]>("SLIDE_IMG_BLOB")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("ID")
                        .HasName("PK_SliderImg");

                    b.ToTable("dbSliderImg");
                });

            modelBuilder.Entity("FinanceApp.Models.TaxEligibility", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("TaxYear")
                        .HasColumnType("int");

                    b.Property<decimal>("AnnualGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CrossingDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DetectionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EligiblePp23")
                        .HasColumnType("char(1)");

                    b.HasKey("CustomerId", "TaxYear");

                    b.ToTable("tax_eligibility");
                });

            modelBuilder.Entity("FinanceApp.Models.dbAccount", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("account_Type")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("account_name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("account_no")
                        .HasColumnType("int");

                    b.Property<string>("akundk")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("akunnrlr")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("company_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("date");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("flag_aktif")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("hierarchy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("date");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK_Account");

                    b.ToTable("dbAccount");
                });

            modelBuilder.Entity("FinanceApp.Models.dbBank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Akun_Credit")
                        .HasColumnType("int");

                    b.Property<int>("Akun_Debit")
                        .HasColumnType("int");

                    b.Property<int>("Credit")
                        .HasColumnType("int(20)");

                    b.Property<int>("Debit")
                        .HasColumnType("int(20)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MonthStr")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Saldo")
                        .HasColumnType("int(20)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("date");

                    b.Property<string>("TransDateStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Trans_no")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("YearStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("company_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("flag_aktif")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("dbBank");
                });

            modelBuilder.Entity("FinanceApp.Models.dbClosedValue", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Akun_Credit")
                        .HasColumnType("int");

                    b.Property<int>("Akun_Debit")
                        .HasColumnType("int");

                    b.Property<string>("company_id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("credit")
                        .HasColumnType("int");

                    b.Property<int>("debit")
                        .HasColumnType("int");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("src")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_DCV");

                    b.ToTable("dbClosedValue");
                });

            modelBuilder.Entity("FinanceApp.Models.dbClosing", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("company_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("datefrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dateto")
                        .HasColumnType("datetime");

                    b.Property<string>("description")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("isclosed")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("periode")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_Closing");

                    b.ToTable("dbClosing");
                });

            modelBuilder.Entity("FinanceApp.Models.dbJm", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Akun_Credit")
                        .HasColumnType("int");

                    b.Property<int>("Akun_Debit")
                        .HasColumnType("int");

                    b.Property<int>("Credit")
                        .HasColumnType("int(20)");

                    b.Property<int>("Debit")
                        .HasColumnType("int(20)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MonthStr")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("date");

                    b.Property<string>("TransDateStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Trans_no")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("YearStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("company_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("flag_aktif")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK_JM");

                    b.ToTable("dbJm");
                });

            modelBuilder.Entity("FinanceApp.Models.dbJpb", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Akun_Credit")
                        .HasColumnType("int");

                    b.Property<int?>("Akun_Credit_disc")
                        .HasColumnType("int");

                    b.Property<int>("Akun_Debit")
                        .HasColumnType("int");

                    b.Property<int?>("Akun_Debit_disc")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MonthStr")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("date");

                    b.Property<string>("TransDateStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Trans_no")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Value")
                        .HasColumnType("int(20)");

                    b.Property<int>("Value_Disc")
                        .HasColumnType("int(20)");

                    b.Property<string>("YearStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("company_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("flag_aktif")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK_JPB");

                    b.ToTable("dbJpb");
                });

            modelBuilder.Entity("FinanceApp.Models.dbJpn", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Akun_Credit")
                        .HasColumnType("int");

                    b.Property<int?>("Akun_Credit_disc")
                        .HasColumnType("int");

                    b.Property<int>("Akun_Debit")
                        .HasColumnType("int");

                    b.Property<int?>("Akun_Debit_disc")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MonthStr")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("date");

                    b.Property<string>("TransDateStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Trans_no")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Value")
                        .HasColumnType("int(20)");

                    b.Property<int>("Value_Disc")
                        .HasColumnType("int(20)");

                    b.Property<string>("YearStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("company_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("flag_aktif")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK_JPN");

                    b.ToTable("dbJpn");
                });

            modelBuilder.Entity("FinanceApp.Models.dbKas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Akun_Credit")
                        .HasColumnType("int");

                    b.Property<int>("Akun_Debit")
                        .HasColumnType("int");

                    b.Property<int>("Credit")
                        .HasColumnType("int(20)");

                    b.Property<int>("Debit")
                        .HasColumnType("int(20)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MonthStr")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Saldo")
                        .HasColumnType("int(20)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("date");

                    b.Property<string>("TransDateStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Trans_no")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("YearStr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("company_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("flag_aktif")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK_Kas");

                    b.ToTable("dbKas");
                });

            modelBuilder.Entity("FinanceApp.Models.dbLd", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("company_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("datetime");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("value")
                        .HasColumnType("bigint(20)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_LD");

                    b.ToTable("dbLd");
                });

            modelBuilder.Entity("FinanceApp.Models.dbTaxConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("entry_date")
                        .HasColumnType("date");

                    b.Property<string>("entry_user")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("flag_aktif")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("taxlimit")
                        .HasColumnType("bigint(20)");

                    b.Property<long>("taxlimitmax")
                        .HasColumnType("bigint(20)");

                    b.Property<long>("taxlimitmin")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("taxmode")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("taxpercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("taxtype")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("date");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("id");

                    b.ToTable("TaxConfigTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
